"""
Bac 3AS Keyword Dictionaries for Video Filtering.

This module contains subject-specific keyword dictionaries aligned with the
Algerian Baccalauréat (3AS) curriculum. Keywords are provided in French,
Arabic, and English to handle multilingual educational content.

Each subject has:
- bac_terms: Keywords that indicate Bac-level content
- exclude_terms: Keywords that indicate lower-grade content (to filter out)
- threshold: Confidence threshold for classification (0.0-1.0)
"""

from typing import Any, Dict, List

# Main keyword dictionary organized by subject
BAC_KEYWORDS: Dict[str, Dict[str, Any]] = {
    "natural_sciences": {
        "subjects": ["Biology", "Life Sciences", "Natural Sciences", "علوم الطبيعة والحياة"],
        "bac_terms": {
            "french": [
                "génétique",
                "adn",
                "arn",
                "chromosome",
                "photosynthèse",
                "respiration",
                "cellule",
                "noyau",
                "évolution",
                "immunité",
                "écosystème",
                "enzyme",
                "mitose",
                "méiose",
                "protéine",
                "synthèse protéique",
                "réplication",
                "transcription",
                "traduction",
                "mutation",
                "allèle",
                "gène",
                "phénotype",
                "génotype",
                "hérédité",
                "brassage génétique",
                "système nerveux",
                "neurone",
                "synapse",
                "réflexe",
                "hormone",
                "régulation",
            ],
            "arabic": [
                "وراثة",
                "حمض نووي",
                "كروموسوم",
                "البناء الضوئي",
                "التنفس الخلوي",
                "خلية",
                "نواة",
                "تطور",
                "المناعة",
                "النظام البيئي",
                "إنزيم",
                "انقسام منصف",
                "انقسام خيطي",
                "بروتين",
                "تركيب البروتين",
                "الطفرة",
                "أليل",
                "مورثة",
                "النمط الظاهري",
                "النمط الوراثي",
                "التهجين",
                "الجهاز العصبي",
                "عصبون",
                "مشبك",
                "منعكس",
                "هرمون",
                "تنظيم",
            ],
            "english": [
                "genetics",
                "dna",
                "rna",
                "chromosome",
                "photosynthesis",
                "respiration",
                "cell",
                "nucleus",
                "evolution",
                "immunity",
                "ecosystem",
                "enzyme",
                "mitosis",
                "meiosis",
                "protein synthesis",
                "replication",
                "transcription",
                "translation",
                "mutation",
                "allele",
                "gene",
                "phenotype",
                "genotype",
                "heredity",
            ],
        },
        "exclude_terms": {
            "french": [
                "classe 1",
                "classe 2",
                "niveau débutant",
                "initiation",
                "découverte",
            ],
            "arabic": [
                "سنة أولى",
                "سنة ثانية",
                "مبتدئ",
            ],
        },
        "threshold": 0.7,
    },
    "mathematics": {
        "subjects": ["Maths", "Mathematics", "Mathématiques", "رياضيات"],
        "bac_terms": {
            "french": [
                "dérivée",
                "intégrale",
                "limite",
                "suite",
                "probabilité",
                "nombre complexe",
                "matrice",
                "déterminant",
                "trigonométrie",
                "fonction exponentielle",
                "fonction logarithmique",
                "primitive",
                "équation différentielle",
                "vecteur",
                "géométrie dans l'espace",
                "continuité",
                "dérivabilité",
                "théorème",
                "convergence",
                "récurrence",
                "dénombrement",
                "loi binomiale",
                "loi normale",
                "espérance",
                "variance",
                "écart type",
                "asymptote",
                "tangente",
            ],
            "arabic": [
                "مشتقة",
                "تكامل",
                "نهاية",
                "متتالية",
                "احتمالية",
                "عدد مركب",
                "مصفوفة",
                "محدد",
                "دالة أسية",
                "دالة لوغاريتمية",
                "دالة مثلثية",
                "اشتقاق",
                "تفاضل",
                "هندسة فضائية",
                "استمرارية",
                "تقاربية",
                "برهان بالتراجع",
                "التوزيع الطبيعي",
                "الأمل الرياضي",
                "التباين",
            ],
            "english": [
                "derivative",
                "integral",
                "limit",
                "sequence",
                "probability",
                "complex number",
                "matrix",
                "determinant",
                "trigonometry",
                "exponential function",
                "logarithmic function",
                "primitive",
                "differential equation",
                "vector",
                "convergence",
                "recurrence",
                "binomial distribution",
                "normal distribution",
                "expectation",
                "variance",
            ],
        },
        "exclude_terms": {
            "french": [
                "équation linéaire simple",
                "polynôme 2e degré",
                "calcul mental",
                "tables de multiplication",
            ],
            "arabic": [
                "جمع وطرح",
                "ضرب وقسمة",
                "حساب ذهني",
            ],
        },
        "threshold": 0.7,
    },
    "physics": {
        "subjects": ["Physics", "Physique", "فيزياء"],
        "bac_terms": {
            "french": [
                "cinématique",
                "dynamique",
                "travail",
                "énergie",
                "thermodynamique",
                "électricité",
                "tension",
                "courant",
                "onde",
                "optique",
                "photon",
                "mécanique",
                "force",
                "mouvement",
                "oscillation",
                "pendule",
                "condensateur",
                "inductance",
                "circuit rlc",
                "électromagnétisme",
                "champ magnétique",
                "induction",
                "radioactivité",
                "décroissance radioactive",
                "noyau atomique",
                "fission",
                "fusion",
                "relativité",
                "effet photoélectrique",
                "spectre",
                "interférences",
                "diffraction",
            ],
            "arabic": [
                "الحركيات",
                "الديناميكا",
                "عمل",
                "طاقة",
                "ديناميكا حرارية",
                "كهربائية",
                "جهد",
                "تيار",
                "موجة",
                "بصريات",
                "فوتون",
                "ميكانيكا",
                "قوة",
                "حركة",
                "تذبذب",
                "نواس",
                "مكثفة",
                "وشيعة",
                "دارة كهربائية",
                "حقل مغناطيسي",
                "حث كهرومغناطيسي",
                "نشاط إشعاعي",
                "تفكك إشعاعي",
                "نواة ذرية",
                "انشطار",
                "اندماج",
                "طيف",
                "تداخل",
                "حيود",
            ],
            "english": [
                "kinematics",
                "dynamics",
                "work",
                "energy",
                "thermodynamics",
                "electricity",
                "voltage",
                "current",
                "wave",
                "optics",
                "photon",
                "mechanics",
                "force",
                "motion",
                "oscillation",
                "pendulum",
                "capacitor",
                "inductance",
                "rlc circuit",
                "electromagnetism",
                "magnetic field",
                "induction",
                "radioactivity",
                "nuclear",
                "fission",
                "fusion",
                "spectrum",
                "interference",
                "diffraction",
            ],
        },
        "exclude_terms": {
            "french": [
                "physique amusante",
                "expériences simples",
            ],
            "arabic": [
                "تجارب بسيطة",
            ],
        },
        "threshold": 0.7,
    },
    "philosophy": {
        "subjects": ["Philosophy", "Philosophie", "فلسفة"],
        "bac_terms": {
            "french": [
                "connaissance",
                "vérité",
                "morale",
                "éthique",
                "liberté",
                "justice",
                "conscience",
                "raisonnement",
                "logique",
                "argumentation",
                "essence",
                "réalité",
                "existence",
                "métaphysique",
                "épistémologie",
                "ontologie",
                "déterminisme",
                "libre arbitre",
                "empirisme",
                "rationalisme",
                "idéalisme",
                "matérialisme",
                "phénoménologie",
                "dialectique",
                "syllogisme",
                "sophisme",
                "dissertation",
                "thèse",
                "antithèse",
                "synthèse",
            ],
            "arabic": [
                "معرفة",
                "حقيقة",
                "أخلاق",
                "حرية",
                "عدالة",
                "وعي",
                "منطق",
                "حجة",
                "جوهر",
                "واقع",
                "وجود",
                "ميتافيزيقا",
                "إبستمولوجيا",
                "أنطولوجيا",
                "حتمية",
                "إرادة حرة",
                "تجريبية",
                "عقلانية",
                "مثالية",
                "مادية",
                "جدلية",
                "قياس منطقي",
                "مغالطة",
                "أطروحة",
                "نقيض الأطروحة",
                "تركيب",
            ],
            "english": [
                "knowledge",
                "truth",
                "morality",
                "ethics",
                "freedom",
                "justice",
                "consciousness",
                "logic",
                "reasoning",
                "argument",
                "essence",
                "reality",
                "existence",
                "metaphysics",
                "epistemology",
                "ontology",
                "determinism",
                "free will",
                "empiricism",
                "rationalism",
                "idealism",
                "materialism",
                "dialectic",
            ],
        },
        "exclude_terms": {
            "french": [
                "philosophie pour enfants",
                "initiation philosophie",
            ],
            "arabic": [
                "فلسفة للأطفال",
            ],
        },
        "threshold": 0.6,  # Lower threshold - philosophy terms are more general
    },
    "french_language": {
        "subjects": ["French", "Français", "فرنسية", "لغة فرنسية"],
        "bac_terms": {
            "french": [
                "analyse littéraire",
                "dissertation",
                "argumentation",
                "subjonctif",
                "figure de style",
                "métaphore",
                "poésie",
                "molière",
                "voltaire",
                "hugo",
                "commentaire composé",
                "explication de texte",
                "synthèse",
                "résumé",
                "compte rendu",
                "narrateur",
                "focalisation",
                "champ lexical",
                "registre",
                "tonalité",
                "ironie",
                "satire",
                "allégorie",
                "personnification",
                "hyperbole",
                "litote",
                "antithèse",
                "oxymore",
                "anaphore",
                "thèse argumentative",
                "connecteurs logiques",
            ],
            "arabic": [
                "تحليل أدبي",
                "مقال",
                "حجاج",
                "شعر",
                "استعارة",
                "تشبيه",
                "سرد",
                "وصف",
            ],
            "english": [
                "literary analysis",
                "essay",
                "argumentation",
                "subjunctive",
                "metaphor",
                "poetry",
                "molière",
                "voltaire",
                "hugo",
                "narrative",
                "irony",
                "satire",
            ],
        },
        "exclude_terms": {
            "french": [
                "conjugaison simple",
                "vocabulaire basique",
                "niveau 1",
                "débutant",
                "alphabet",
            ],
            "arabic": [
                "تعلم الفرنسية",
                "مبتدئ",
            ],
        },
        "threshold": 0.7,
    },
    "english_language": {
        "subjects": ["English", "Anglais", "إنجليزية", "لغة إنجليزية"],
        "bac_terms": {
            "english": [
                "advanced grammar",
                "conditional",
                "passive voice",
                "essay writing",
                "reading comprehension",
                "idiomatic expressions",
                "phrasal verbs",
                "british literature",
                "american literature",
                "shakespeare",
                "reported speech",
                "relative clauses",
                "subjunctive",
                "formal writing",
                "academic writing",
                "thesis statement",
                "topic sentence",
                "paragraph structure",
                "cohesion",
                "coherence",
            ],
            "french": [
                "grammaire avancée",
                "conditionnel",
                "voix passive",
                "rédaction",
                "compréhension écrite",
                "expressions idiomatiques",
            ],
            "arabic": [
                "قواعد متقدمة",
                "كتابة مقال",
                "فهم النص",
            ],
        },
        "exclude_terms": {
            "english": [
                "basic grammar",
                "beginner",
                "elementary",
                "simple vocabulary",
                "alphabet",
                "numbers",
            ],
            "french": [
                "anglais débutant",
                "bases anglais",
            ],
            "arabic": [
                "تعلم الإنجليزية",
                "مبتدئ",
            ],
        },
        "threshold": 0.7,
    },
    "arabic_language": {
        "subjects": ["Arabic", "Arabe", "عربية", "لغة عربية", "أدب عربي"],
        "bac_terms": {
            "arabic": [
                "أدب",
                "شعر",
                "نثر",
                "رواية",
                "الأدب الحديث",
                "البلاغة",
                "إعراب",
                "تحليل النص",
                "شرح النص",
                "المقالة الأدبية",
                "القرآن الكريم",
                "الحديث الشريف",
                "نحو",
                "صرف",
                "معاني",
                "بيان",
                "بديع",
                "استعارة",
                "كناية",
                "تشبيه",
                "جناس",
                "طباق",
                "مقابلة",
                "النص الحجاجي",
                "النص السردي",
                "النص الوصفي",
                "العصر الجاهلي",
                "العصر الأموي",
                "العصر العباسي",
                "الأدب المعاصر",
            ],
            "french": [
                "littérature arabe",
                "poésie arabe",
                "grammaire arabe",
                "rhétorique arabe",
            ],
        },
        "exclude_terms": {
            "arabic": [
                "قواعد بسيطة",
                "مستوى أول",
                "لغة أطفال",
                "تعلم القراءة",
                "الحروف",
            ],
            "french": [
                "arabe débutant",
            ],
        },
        "threshold": 0.7,
    },
    "islamic_sciences": {
        "subjects": ["Islamic Sciences", "Sciences Islamiques", "علوم إسلامية", "تربية إسلامية"],
        "bac_terms": {
            "arabic": [
                "تفسير",
                "قرآن",
                "حديث",
                "فقه",
                "شريعة",
                "تاريخ الإسلام",
                "السيرة النبوية",
                "أخلاق إسلامية",
                "فلسفة إسلامية",
                "عقيدة",
                "توحيد",
                "أصول الفقه",
                "علوم القرآن",
                "علوم الحديث",
                "مقاصد الشريعة",
                "الإجماع",
                "القياس",
                "الاجتهاد",
                "الفتوى",
                "الحلال والحرام",
            ],
            "french": [
                "exégèse",
                "tafsir",
                "hadith",
                "jurisprudence",
                "sharia",
                "histoire de l'islam",
                "sirah",
                "éthique islamique",
                "sciences coraniques",
            ],
            "english": [
                "quran",
                "hadith",
                "islamic jurisprudence",
                "sharia",
                "islamic history",
                "prophetic biography",
                "islamic ethics",
            ],
        },
        "exclude_terms": {
            "arabic": [
                "للأطفال",
                "قصص الأنبياء للصغار",
            ],
        },
        "threshold": 0.65,
    },
    "history_geography": {
        "subjects": ["History", "Geography", "Histoire", "Géographie", "تاريخ", "جغرافيا"],
        "bac_terms": {
            "french": [
                "histoire contemporaine",
                "xxe siècle",
                "guerre mondiale",
                "décolonisation",
                "indépendance",
                "guerre d'algérie",
                "révolution algérienne",
                "géopolitique",
                "géographie",
                "guerre froide",
                "mouvement national",
                "colonisation",
                "impérialisme",
                "nationalisme",
                "mondialisation",
                "développement",
                "sous-développement",
                "tiers monde",
                "organisation internationale",
                "onu",
                "otan",
                "union européenne",
                "ligue arabe",
                "union africaine",
            ],
            "arabic": [
                "التاريخ الحديث",
                "القرن العشرين",
                "حرب عالمية",
                "إلغاء استعمار",
                "استقلال",
                "ثورة جزائرية",
                "جغرافيا",
                "الحرب الباردة",
                "الحركة الوطنية",
                "الاستعمار",
                "الإمبريالية",
                "القومية",
                "العولمة",
                "التنمية",
                "العالم الثالث",
                "الأمم المتحدة",
                "جامعة الدول العربية",
                "الاتحاد الأفريقي",
                "أول نوفمبر",
                "اتفاقيات إيفيان",
            ],
            "english": [
                "modern history",
                "20th century",
                "world war",
                "decolonization",
                "algerian revolution",
                "geopolitics",
                "geography",
                "cold war",
                "national movement",
                "colonization",
                "imperialism",
                "nationalism",
                "globalization",
                "development",
                "united nations",
            ],
        },
        "exclude_terms": {
            "french": [
                "histoire pour enfants",
                "géographie amusante",
            ],
            "arabic": [
                "تاريخ للأطفال",
            ],
        },
        "threshold": 0.65,
    },
}

# Grade level indicators - used for explicit grade detection
GRADE_INDICATORS: Dict[str, List[str]] = {
    "bac_markers": [
        # Arabic
        "بكالوريا",
        "باك",
        "شهادة البكالوريا",
        "ثالثة ثانوي",
        "السنة الثالثة ثانوي",
        "3 ثانوي",
        # French
        "bac",
        "bacalauréat",
        "terminale",
        "3as",
        "troisième année secondaire",
        "3ème année secondaire",
        # Mixed
        "bac 2024",
        "bac 2025",
        "bac 2026",
        "باك 2024",
        "باك 2025",
        "باك 2026",
    ],
    "exclude_markers": [
        # First year secondary
        "1as",
        "1 as",
        "سنة أولى ثانوي",
        "أولى ثانوي",
        "1ère année secondaire",
        "première année secondaire",
        # Second year secondary
        "2as",
        "2 as",
        "سنة ثانية ثانوي",
        "ثانية ثانوي",
        "2ème année secondaire",
        "deuxième année secondaire",
        # Middle school
        "متوسط",
        "1am",
        "2am",
        "3am",
        "4am",
        "bem",
        "شهادة التعليم المتوسط",
        # Primary
        "ابتدائي",
        "5ap",
        # General exclusions
        "débutant",
        "beginner",
        "مبتدئ",
        "initiation",
    ],
}


def get_all_bac_keywords() -> List[str]:
    """Get a flat list of all Bac-related keywords across all subjects."""
    all_keywords = []
    for subject_dict in BAC_KEYWORDS.values():
        for lang_keywords in subject_dict["bac_terms"].values():
            all_keywords.extend(lang_keywords)
    return list(set(all_keywords))


def get_all_exclude_keywords() -> List[str]:
    """Get a flat list of all exclusion keywords across all subjects."""
    all_excludes = []
    for subject_dict in BAC_KEYWORDS.values():
        exclude_terms = subject_dict.get("exclude_terms", {})
        for lang_keywords in exclude_terms.values():
            all_excludes.extend(lang_keywords)
    # Add grade-level exclusions
    all_excludes.extend(GRADE_INDICATORS["exclude_markers"])
    return list(set(all_excludes))
